---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
    run_list:
    - recipe[yum]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]


suites:
  - name: default
    run_list:
      - recipe[wrapper::default]
